### ISSUE TITLE
Cidadão -  incluir novo destaque

### ISSUE THREAD

**Issue by helenhilario** [EscolaDeSaudePublica/coronavirus.ceara.gov.br#20]
3. Criar a nova aba na página do cidadão (relatório da reunião deve ser compartilhado pela Clarisse) que foi definida na reunião de sexta-feira (nessa aba inserir as peças publicitárias do governo do estado, SESA e demais materiais com orientações para a população; 

Na  página "Cidadão" (https://coronavirus.ceara.gov.br/cidadao/)
incluir outra caixa entre "Telesaude" e "Perguntas Frequentes" com o conteúdo disponível em Dowload disponível em (https://www.saude.ce.gov.br/coronavirus-covid-19/) 

Texto maior: "Seja você também um agente de combate do Coronavírus". 
Texto menor: "Baixe aqui materiais confiáveis para compartilhar em suas redes"

Procurar o seguinte conteúdo na pagina indicada acima:
[Faça o download
    Cartaz Coronavírus (Covid-19)
    Cartilha Etiqueta da Tosse (Covid-19)
    Cartaz Higienização das Mãos (álcool em gel/água e sabão)
    Cartilha Prevenção e Cuidados (Covid-19)
    Cartilha Precauções em Domicílios (Covid-19)]

**Comment by Junior-Shyko** [comment]
Criado um link na página cidadão e home apontando para um post com os arquivos.
https://coronavirus.ceara.gov.br/download/
