### ISSUE TITLE
Inserir links para compartilhamento de PDFs por WhatsApp

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/coronavirus.ceara.gov.br#48]
## **Objetivo**

**Como** usuária do Manejo Clínico Covid-19
**Quero** compartilhar links de PDFs por WahtsApp
**Para** meus contatos acessarem diretamente os conteúdos indicados por mim

## **Contexto**
As páginas "Fluxos de tratamento para Insuficiência Respiratória Aguda por Covid-19" e "Cenários de Atendimento" possuem arquivos no formato PDF para download. Há possibilidade de compartilhar a página em si, porém, há usuárias que desejam compartilhar apenas o link do PDF diretamente por WhatsApp, para que as usuárias que receberem este link não vejam o site, mas apenas o PDF. Apesar disso poder gerar a perda de contexto oferecida pelo conteúdos das páginas, avalia-se que os profissionais têm a necessidade de receber os conteúdos específicos, de forma isolada.
Não há suporte neste momento para implementação com lógica de programação, os links devem ser inseridos manualmente, seguindo a sintaxe da API do WhatsApp.

### **Narativas**
- [x] Redigir texto de compartilhamento para cada um dos PDFs disponíveis nas páginas [Cenários de Atendimento](https://coronavirus.ceara.gov.br/profissional/manejoclinico/cenarios-de-atendimento/) (3) e [Fluxos IRPA](https://coronavirus.ceara.gov.br/profissional/manejoclinico/fluxos-irpa/) (6).

### **UX Design**

**Cenários de Atendimento**
- [x] Fazer download dos PDFs de cada aba
- [x] Renomear o arquivo para o mesmo título da página. Ex.: "Cenários de atendimento - Enfermaria.pdf"
- [x] Fazer upload no Drive, na pasta Hotsite Corona > PDFs Públicos
- [x] Copiar o link público do PDF e gerar link curto
- [x] Gerar link de compartilhamento no WhatsApp com a mensagem de compartilhamento e o link curto
- [x] Inserir botão "Compartilhar no WhatsApp" com CSS inline ao lado do botão "Baixar PDF" de cada aba

**Fluxos IRPA**
- [x] Fazer download dos PDFs de cada fluxo
- [x] Renomear o arquivo para o mesmo título do fluxo
- [x] Fazer upload no Drive, na pasta Hotsite Corona > PDFs Públicos
- [x] Copiar o link público do PDF e gerar link curto
- [x] Gerar link de compartilhamento no WhatsApp com a mensagem de compartilhamento e o link curto
- [x] Inserir botão "Compartilhar no WhatsApp" com o módulo de botão abaixo de cada módulo sinopse

## **Critérios de Aceitação**

- [x] Compartilhamento desktop (Whats Web)
**Dado que** acesso as páginas "Suporte Ventilatório" e "Cenários de Atendimento"
**E** não possuo o aplicativo desktop do WhatsApp
**Quando** clico nos botão de compartilhamento do WhatsApp na página
**Então** serei direcionado para o WhatsApp Web com a mensagem pré-definida

- [x] Compartilhamento desktop (Whats Desktop)
**Dado que** acesso as páginas "Suporte Ventilatório" e "Cenários de Atendimento"
**E** possuo o aplicativo desktop do WhatsApp
**Quando** clico nos botão de compartilhamento do WhatsApp nas páginas
**Então** verei a janela do WhatsApp Desktop solicitando os contatos para quem desejo enviar a mensagem pré-definida

- [x] Compartilhamento mobile
**Dado que** acesso as páginas "Suporte Ventilatório" e "Cenários de Atendimento"
**Quando** clico nos botão de compartilhamento do WhatsApp nas páginas
**Então** verei o app WhatsApp solicitando os contatos para quem desejo enviar a mensagem pré-definida

## Observações
**Sintaxe para links de compartilhamento no WhatsApp**
`https://api.whatsapp.com/send?text=TEXTO_DE_COMPARTILHAMENTO`

**Exemplo**
Link inserido:
`https://api.whatsapp.com/send?text=Confira%20as%20principais%20recomenda%C3%A7%C3%B5es%20de%20atendimento%20ambulatorial%20para%20pacientes%20com%20suspeita%20de%20Covid-19%20%5Blink%5D`

Mensagem gerada:
Confira as principais recomendações de atendimento ambulatorial para pacientes com suspeita de Covid-19 [link]

Codificador de texto para URL
https://www.urlencoder.org/

**Comment by ClarisCaval** [comment]
Aqui a sugestão para os textinhos:
https://docs.google.com/document/d/1_EMPVm_Qp88z10ouhs3mOB1v9AYGDrfxHh1TIag69nM/edit
