### ISSUE TITLE
Implementar páginas no DIVI wordpress

### ISSUE THREAD

**Issue by vicmagpac** [EscolaDeSaudePublica/coronavirus.ceara.gov.br#9]
- [ ] Página home
- [ ] Página profissional de saúde
- [ ] Página cidadão
- [ ] Página postagens (postagem)
- [ ] Página perguntas frequentes

**Comment by ItaloRod** [comment]
Cidadão:
- [x] Tirar o Texto inicial
- [x] Tirar os Botões
- [ ] Tirar os Links recomendáveis das perguntas e respostas
- [ ] Tirar os Links de Downloads das Perguntas e respostas
